### ISSUE TITLE
unresolved shape for simpleRestJson

### ISSUE THREAD

**Issue by MoeQuadrat** [iancaffey/smithy-intellij-plugin#6]
Hi, 
after updating to the current version, i cant seem to figure out how to fix my folder structure to resolve these issues.

![image](https://user-images.githubusercontent.com/53238135/199432907-8385bf7d-d3c0-446e-ac4a-3e4f9508c779.png)

![image](https://user-images.githubusercontent.com/53238135/199436327-dc539a5e-9c25-4680-ae6e-cc6349bd2c63.png)

any ideas to fix my issues?

**Comment by iancaffey** [comment]
Can you share more about how you've setup the project/module in IntelliJ (build system and everything)? 

The plugin will find traits from all transitive dependencies, so how that gets setup can vary across build systems. 

A crude way of seeing if any outdated caches in the plugin were causing resolution problems would be to invalidate caches in IntelliJ (making sure to select the first option which deletes all file indexes).

**Comment by MoeQuadrat** [comment]
Adding smithy4s-protocols resolved the issues. Codegen from smithy4s was working just fine so i figured the dependencies were alright. But i guess i was wrong :D 
Thanks!

**Comment by iancaffey** [comment]
Older versions of the plugin just kind of _found_ all dependencies within your project, not respecting the IntelliJ module structure. So that might have been what you were experiencing before?

So newer versions require a little more ceremony with getting things in order (to work in multi-module projects and better support all build systems), but after that, doesn't require anything too special. 

Glad everything got sorted! :)
